name 'puppet-xmpp'
version '0.0.1'
license 'Apache 2.0'
summary 'A Puppet report handler for sending notifications of failed runs to Jabber/XMPP'
project_page 'https://github.com/jamtur01/puppet-xmpp'
